out/bin/additions/src/vboxguest/*.* /usr/src/modules/virtualbox-ose-guest/vboxguest
out/bin/additions/src/vboxguest/common /usr/src/modules/virtualbox-ose-guest/vboxguest
out/bin/additions/src/vboxguest/generic /usr/src/modules/virtualbox-ose-guest/vboxguest
out/bin/additions/src/vboxguest/VBox /usr/src/modules/virtualbox-ose-guest/vboxguest
out/bin/additions/src/vboxguest/build_in_tmp /usr/src/modules/virtualbox-ose-guest/vboxguest
out/bin/additions/src/vboxguest/Makefile /usr/src/modules/virtualbox-ose-guest/vboxguest

out/bin/additions/src/vboxvfs/*.* /usr/src/modules/virtualbox-ose-guest/vboxvfs
out/bin/additions/src/vboxvfs/build_in_tmp /usr/src/modules/virtualbox-ose-guest/vboxvfs
out/bin/additions/src/vboxvfs/Makefile /usr/src/modules/virtualbox-ose-guest/vboxvfs

out/bin/additions/src/vboxvideo/*.* /usr/src/modules/virtualbox-ose-guest/vboxvideo
out/bin/additions/src/vboxvideo/build_in_tmp /usr/src/modules/virtualbox-ose-guest/vboxvideo
out/bin/additions/src/vboxvideo/Makefile /usr/src/modules/virtualbox-ose-guest/vboxvideo

out/bin/additions/src/vboxguest/include/iprt/* /usr/src/modules/virtualbox-ose-guest/include/iprt
out/bin/additions/src/vboxguest/include/VBox/* /usr/src/modules/virtualbox-ose-guest/include/VBox
out/bin/additions/src/vboxguest/include/internal/* /usr/src/modules/virtualbox-ose-guest/include/internal

out/bin/additions/src/vboxvfs/include/iprt/* /usr/src/modules/virtualbox-ose-guest/include/iprt
out/bin/additions/src/vboxvfs/include/VBox/* /usr/src/modules/virtualbox-ose-guest/include/VBox

out/bin/additions/src/vboxguest/r0drv /usr/src/modules/virtualbox-ose-guest/

debian/virtualbox-ose-guest-source.files/Makefile /usr/src/modules/virtualbox-ose-guest
debian/virtualbox-ose-guest-source.files/control.modules.in /usr/src/modules/virtualbox-ose-guest/debian
debian/virtualbox-ose-guest-source.files/rules /usr/src/modules/virtualbox-ose-guest/debian
debian/control debian/changelog debian/copyright debian/compat /usr/src/modules/virtualbox-ose-guest/debian
