#!/bin/sh

set -e

case "${1}" in
	purge)
		# Removing vboxusers group
		if [ -x /usr/sbin/delgroup ]
		then
			# delgroup may return error status 3 if there is a non-system group
			# "vboxusers". The postrm should not fail in this case!
			delgroup --quiet --system vboxusers || true
		fi
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
