#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]
  then
  exit 0
fi


setup_vboxusers_group() {
        if ! getent group vboxusers >/dev/null; then
                addgroup --quiet --system vboxusers
        fi
}

setup_vboxusers_group

# just in case the system is running without inotify tell udev to reload the rules
if [ -x /sbin/udevcontrol ]; then
	/sbin/udevcontrol reload_rules || true;
fi

#DEBHELPER#

exit 0
