out/bin/additions/VBoxClient /usr/bin
src/VBox/Additions/x11/Installer/x11config.pl /usr/share/virtualbox
src/VBox/Additions/x11/Installer/98vboxadd-xclient /etc/X11/Xsession.d
out/bin/additions/VBoxOGL*.so /usr/lib
out/bin/additions/VBoxEGL*.so /usr/lib
out/bin/additions/VBoxOGL*.so /usr/lib/virtualbox/additions
out/bin/additions/VBoxEGL*.so /usr/lib/virtualbox/additions

debian/virtualbox-guest-x11.files/00vboxvideo.conf /usr/lib/virtualbox/additions
