#!/bin/sh

set -e

case "${1}" in
	configure)
		# Adding vboxusers group
		if ! getent group vboxusers > /dev/null
		then
			addgroup --quiet --system vboxusers
		fi

		# In case the system is running without inotify tell udev to
		# reload the rules
		if [ -x /sbin/udevcontrol ]
		then
			/sbin/udevcontrol reload_rules || true
		fi
		;;

	abort-upgrade|abort-deconfigure|abort-remove)

		;;

	*)
		echo "${0} called with unknown argument \`${1}'" 1>&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
