# $Id: Makefile.kmk $
## @file
# Sub-Makefile for the lwip library.
#

#
# Copyright (C) 2025 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Core lwip library.
#
LIBRARIES += VBox-lwip
VBox-lwip_TEMPLATE := VBoxR3DllNonPedantic
VBox-lwip_INCS = \
	src/include \
	src/include/ipv4 \
	src/include/ipv6 \
	vbox/include \
	vbox
VBox-lwip_SOURCES = \
	src/api/api_lib.c \
	src/api/api_msg.c \
	src/api/err.c \
	src/api/if_api.c \
	src/api/netbuf.c \
	src/api/netdb.c \
	src/api/netifapi.c \
	src/api/sockets.c \
	src/api/tcpip.c \
	\
	src/core/ipv4/acd.c \
	src/core/ipv4/autoip.c \
	src/core/ipv4/dhcp.c \
	src/core/ipv4/etharp.c \
	src/core/ipv4/icmp.c \
	src/core/ipv4/igmp.c \
	src/core/ipv4/ip4.c \
	src/core/ipv4/ip4_addr.c \
	src/core/ipv4/ip4_frag.c \
	\
	src/core/ipv6/dhcp6.c \
	src/core/ipv6/ethip6.c \
	src/core/ipv6/icmp6.c \
	src/core/ipv6/inet6.c \
	src/core/ipv6/ip6.c \
	src/core/ipv6/ip6_addr.c \
	src/core/ipv6/ip6_frag.c \
	src/core/ipv6/mld6.c \
	src/core/ipv6/nd6.c \
	\
	src/core/altcp.c \
	src/core/altcp_alloc.c \
	src/core/altcp_tcp.c \
	src/core/def.c \
	src/core/dns.c \
	src/core/inet_chksum.c \
	src/core/init.c \
	src/core/ip.c \
	src/core/mem.c \
	src/core/memp.c \
	src/core/netif.c \
	src/core/pbuf.c \
	src/core/raw.c \
	src/core/stats.c \
	src/core/sys.c \
	src/core/tcp.c \
	src/core/tcp_in.c \
	src/core/tcp_out.c \
	src/core/timeouts.c \
	src/core/udp.c \
	src/netif/ethernet.c \
	vbox/sys_arch.c \
	vbox/VBoxLwipCore.cpp

LIBRARIES += VBox-lwip-dhcp
VBox-lwip-dhcp_EXTENDS := VBox-lwip
VBox-lwip-dhcp_DEFS += VBOX_LWIP_DHCP

include $(FILE_KBUILD_SUB_FOOTER)
